# Generated by Django 4.1.4 on 2023-03-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duedate', models.DateField()),
                ('amt', models.BigIntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Coders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('qualification', models.ImageField(upload_to='')),
                ('psw', models.CharField(max_length=20)),
                ('contact', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50, null=True)),
                ('lang', models.CharField(max_length=20, null=True)),
                ('skills', models.CharField(max_length=20, null=True)),
                ('profile', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=20)),
                ('receiver', models.EmailField(max_length=254)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='URegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('tforw', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('amount', models.BigIntegerField(null=True)),
                ('bidid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GEEK.bid')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GEEK.coders')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GEEK.uregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=20)),
                ('duedate', models.DateField()),
                ('rfile', models.ImageField(upload_to='')),
                ('status', models.CharField(max_length=20)),
                ('buid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GEEK.uregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amt', models.BigIntegerField()),
                ('buid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GEEK.uregistration')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GEEK.coders')),
                ('wid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GEEK.work')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='buid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GEEK.uregistration'),
        ),
        migrations.AddField(
            model_name='bid',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GEEK.coders'),
        ),
        migrations.AddField(
            model_name='bid',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GEEK.request'),
        ),
    ]
