# Generated by Django 4.1.4 on 2023-03-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GEEK', '0002_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='coders',
            name='alert',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
