# Generated by Django 4.1.4 on 2023-03-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GEEK', '0003_coders_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coders',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
